import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/Navbar";
import { DataContext, DataProvider } from "@/components/shared/DataContex";
import Footer from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sailor | Life style",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        cz-shortcut-listen="true"
      >
        <div className="overflow-hidden">
          <DataProvider>
            <Navbar />
            {children}
            <Footer />
          </DataProvider>
        </div>
      </body>
    </html>
  );
}
